

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_REQUEST';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_REQUEST';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_REQUEST';

export const GET_PRODUCT_BY_RESTAURANT_ID_REQUEST = 'GET_PRODUCT_BY_RESTAURANT_ID_REQUEST';
export const GET_PRODUCT_BY_RESTAURANT_ID_SUCCESS = 'GET_PRODUCT_BY_RESTAURANT_ID_SUCCESS';
export const GET_PRODUCT_BY_RESTAURANT_ID_FAILURE = 'GET_PRODUCT_BY_RESTAURANT_ID_REQUEST';

export const DELETE_MENU_ITEM_REQUEST = 'DELETE_MENU_ITEM_REQUEST';
export const DELETE_MENU_ITEM_SUCCESS = 'DELETE_MENU_ITEM_SUCCESS';
export const DELETE_MENU_ITEM_FAILURE = 'DELETE_MENU_ITEM_REQUEST';

export const SEARCH_MENU_ITEM_REQUEST = 'SEARCH_MENU_ITEM_REQUEST';
export const SEARCH_MENU_ITEM_SUCCESS = 'SEARCH_MENU_ITEM_SUCCESS';
export const SEARCH_MENU_ITEM_FAILURE = 'SEARCH_MENU_ITEM_REQUEST';

export const UPDATE_MENU_ITEMS_AVAILABILITY_REQUEST = 'DELETE_MENU_ITEM_REQUEST';
export const UPDATE_MENU_ITEMS_AVAILABILITY_SUCCESS = 'UPDATE_MENU_ITEMS_AVAILABILITY_SUCCESS';
export const UPDATE_MENU_ITEMS_AVAILABILITY_FAILURE = 'UPDATE_MENU_ITEMS_AVAILABILITY_REQUEST';

export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_REQUEST';

export const COUNT_PRODUCT_AVAILABLE_REQUEST = 'COUNT_PRODUCT_AVAILABLE_REQUEST';
export const COUNT_PRODUCT_AVAILABLE_SUCCESS = 'COUNT_PRODUCT_AVAILABLE_SUCCESS';
export const COUNT_PRODUCT_AVAILABLE_FAILURE = 'COUNT_PRODUCT_AVAILABLE_REQUEST';