export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const GET_USERS_ORDERS_REQUEST = 'GET_USERS_ORDERS_REQUEST';
export const GET_USERS_ORDERS_SUCCESS = 'GET_USERS_ORDERS_SUCCESS';
export const GET_USERS_ORDERS_FAILURE = 'GET_USERS_ORDERS_FAILURE';

export const GET_TOTAL_PRICE_ORDERS_REQUEST = 'GET_TOTAL_PRICE_ORDERS_REQUEST';
export const GET_TOTAL_PRICE_ORDERS_SUCCESS = 'GET_TOTAL_PRICE_ORDERS_SUCCESS';
export const GET_TOTAL_PRICE_ORDERS_FAILURE = 'GET_TOTAL_PRICE_ORDERS_FAILURE';

export const GET_TOTAL_ORDERS_REQUEST = 'GET_TOTAL_ORDERS_REQUEST';
export const GET_TOTAL_ORDERS_SUCCESS = 'GET_TOTAL_ORDERS_SUCCESS';
export const GET_TOTAL_ORDERS_FAILURE = 'GET_TOTAL_ORDERS_FAILURE';

export const GET_USERS_NOTIFICATION_REQUEST = 'GET_USERS_NOTIFICATION_REQUEST';
export const GET_USERS_NOTIFICATION_SUCCESS = 'GET_USERS_NOTIFICATION_SUCCESS';
export const GET_USERS_NOTIFICATION_FAILURE = 'GET_USERS_NOTIFICATION_FAILURE';

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const GET_ORDERSID_REQUEST = 'GET_ORDERSID_REQUEST';
export const GET_ORDERSID_SUCCESS = 'GET_ORDERSID_SUCCESS';
export const GET_ORDERSID_FAILURE = 'GET_ORDERSID_FAILURE';

export const UPDATE_ORDERS_REQUEST = 'UPDATE_ORDERS_REQUEST';
export const UPDATE_ORDERS_SUCCESS = 'UPDATE_ORDERS_SUCCESS';
export const UPDATE_ORDERS_FAILURE = 'UPDATE_ORDERS_FAILURE';