export const GET_CATEGORYITEM = 'GET_CATEGORYITEM';
//export const UPDATE_STOCK = 'UPDATE_STOCK';

export const CREATE_CATEGORYITEM_REQUEST='CREATE_CATEGORYITEM_REQUEST';
export const CREATE_CATEGORYITEM_SUCCESS='CREATE_CATEGORYITEM_SUCCESS';
export const CREATE_CATEGORYITEM_FAILURE='CREATE_CATEGORYITEM_FAILURE';

export const CREATE_CATEGORY_REQUEST='CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS='CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE='CREATE_CATEGORY_FAILURE';

export const GET_CATEGORY_REQUEST='GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS';
export const GETY_CATEGORY_FAILURE='GET_CATEGORY_FAILURE';

export const GET_CATEGORY_REQUEST1='GET_CATEGORY_REQUEST1';
export const GET_CATEGORY_SUCCESS1='GET_CATEGORY_SUCCESS1';
export const GETY_CATEGORY_FAILURE1='GET_CATEGORY_FAILURE1';

export const DELETE_CATEGORY_REQUEST='DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS='DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE='DELETE_CATEGORY_FAILURE';

export const UPDATE_CATEGORY_REQUEST='UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS='UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE='UPDATE_CATEGORY_FAILURE';

export const GET_CATEGORY_ITEMS_REQUEST = 'GET_CATEGORY_ITEMS_REQUEST';
export const GET_CATEGORY_ITEMS_SUCCESS = 'GET_CATEGORY_ITEMS_SUCCESS';
export const GET_CATEGORY_ITEMS_FAILURE = 'GET_CATEGORY_ITEMS_FAILURE';
